baseURL = "https://ms8music.com"
title = "Masa (Neo City Pop Artist)"
theme = "meghna-hugo"
#languageCode = "ja"
DefaultContentLanguage = "en"
[languages]
  [languages.ja]
    weight = 1
    url = "/"
    [languages.ja.params]
        langbutton = "Eng"

  [languages.en]
    weight = 2
    url = "/en/"
    [languages.en.params]
        langbutton = "日本語"


# Menu
[menu]
    [[menu.nav]]
    name = "Bio"
    URL = "bio"
    weight = 1

    [[menu.nav]]
    name = "YouTube"
    URL = "videos"
    weight = 2

    [[menu.nav]]
    name = "Contact"
    URL = "contact"
    weight = 3

[permalinks]
  pages = "/:filename/"

# Site params
[params]
home= "Home"
subtitle = "Singer-songwriter & guitarist"
author = "Masa"
twitterAccount = "@neo_citypop"
description = "A Neo City Pop artist from Japan, who has played TVCM, festivals & gigs over 30 cities. ネオシティポップ（モダンなシティポップ）系シンガーソングライター・ギタリスト。ドイツTVCM参加、ヨーロッパのフェスティバルを含む10ヶ国25都市で演奏。"
logo = ""
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBI14J_PNWVd-m0gnUBkjmhoQyNyd7nllA"
custom_css = []

    # Banner Section
    [params.banner]
    enable = true
    youtubeURL = "https://www.youtube.com/embed/WWDOhnUylXg"
    bgImage = "images/slider/hero-area.jpg"
    heading = "No Matter What, No Matter Where - Masa"
#    content= "My original song"

    # footer
    [params.footer]
        copyright = "Themefisher Team"
        copyrightURL = "http://www.themefisher.com"

        # social Icon
        [[params.footer.socialIcon]]
        icon = "tf-ion-social-youtube"
        url = "https://www.youtube.com/channel/UCy3GKEYNPXgydRmLTCU9Qgw/"

        [[params.footer.socialIcon]]
        icon = "tf-ion-music-note"
        url = "https://open.spotify.com/artist/3JrRIRDZ53fQxe3mlu2TiT?si=1isKoHAaSGKST1vYpNaR-g"

        [[params.footer.socialIcon]]
        icon = "tf-ion-chatboxes"
        url = "https://discord.gg/QyEQBY6"

        [[params.footer.socialIcon]]
        icon = "tf-ion-social-instagram"
        url = "https://www.instagram.com/neo_citypop/"

        [[params.footer.socialIcon]]
        icon = "tf-ion-social-twitter"
        url = "https://twitter.com/neo_citypop"