baseURL = "https://ms8music.com"
languageCode = "ja"
title = "Mamoru Satoh"
theme = "meghna-hugo"

# Menu
[menu]
    [[menu.nav]]
    name = "Bio"
    URL = "bio"
    weight = 1

    [[menu.nav]]
    name = "Live"
    URL = "live"
    weight = 2

    [[menu.nav]]
    name = "Music"
    URL = "music"
    weight = 3

    [[menu.nav]]
    name = "Videos"
    URL = "videos"
    weight = 4

    [[menu.nav]]
    name = "Contact"
    URL = "contact"
    weight = 5

[permalinks]
  pages = "/:filename/"

# Site params
[params]
home= "Home"
subtitle = "Singer-songwriter/guitarist"
author = "Mamoru Satoh"
twitterAccount = "@ms8_music"
description = "ロンドンの音楽学校を卒業後、単身で10ヶ国20都市をバスキングしながら、英語での作詞作曲活動を続ける。2018年より、日本での音楽活動を開始。"
logo = ""
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBI14J_PNWVd-m0gnUBkjmhoQyNyd7nllA"
custom_css = ["css/custom.css"]

    # Banner Section
    [params.banner]
    enable = true
    youtubeURL = "https://www.youtube.com/embed/6RSmITR8jAk"
    bgImage = "images/slider/hero-area.jpg"
    heading = "Mamoru Satoh"
    content= "シンガーソングライター・ギタリスト"

    # footer
    [params.footer]
        copyright = "Themefisher Team"
        copyrightURL = "http://www.themefisher.com"

        # social Icon
        [[params.footer.socialIcon]]
        icon = "tf-ion-social-instagram"
        url = "https://www.instagram.com/ms8music/"

        [[params.footer.socialIcon]]
        icon = "tf-ion-social-twitter"
        url = "https://twitter.com/ms8_music"

         [[params.footer.socialIcon]]
        icon = "tf-ion-social-facebook"
        url = "https://www.facebook.com/ms8music/"

        [[params.footer.socialIcon]]
        icon = "tf-ion-social-youtube"
        url = "https://www.youtube.com/channel/UCwEuF04qnE0QI4FVJg1o2sg"
